
module tsisolib.util {
    export class Keyboard {
        static A = 65;
        static B = 66;
        static C = 67;
        static D = 68;
        static E = 69;
        static F = 70;
        static G = 71;
        static H = 72;
        static I = 73;
        static J = 74;
        static K = 75;
        static L = 76;
        static M = 77;
        static N = 78;
        static O = 79;
        static P = 80;
        static Q = 81;
        static R = 82;
        static S = 83;
        static T = 84;
        static U = 85;
        static V = 86;
        static W = 87;
        static X = 88;
        static Y = 89;
        static Z = 90;

        static F1 = 112;
        static F2 = 113;
        static F3 = 114;
        static F4 = 115;
        static F5 = 116;
        static F6 = 117;
        static F7 = 118;
        static F8 = 119;
        static F9 = 120;
        static F10 = 121;
        static F11 = 122;
        static F12 = 123;
        static F13 = 124;
        static F14 = 125;
        static F15 = 126;

        static NUMBER_0 = 48;
        static NUMBER_1 = 49;
        static NUMBER_2 = 50;
        static NUMBER_3 = 51;
        static NUMBER_4 = 52;
        static NUMBER_5 = 53;
        static NUMBER_6 = 54;
        static NUMBER_7 = 55;
        static NUMBER_8 = 56;
        static NUMBER_9 = 57;

        static NUMPAD = 21;
        static NUMPAD_0 = 96;
        static NUMPAD_1 = 97;
        static NUMPAD_2 = 98;
        static NUMPAD_3 = 90;
        static NUMPAD_4 = 100;
        static NUMPAD_5 = 101;
        static NUMPAD_6 = 102;
        static NUMPAD_7 = 103;
        static NUMPAD_8 = 104;
        static NUMPAD_9 = 105;
        static NUMPAD_MULTIPLY = 106;
        static NUMPAD_ADD = 107;
        static NUMPAD_ENTER = 108;
        static NUMPAD_SUBTRACT = 109;
        static NUMPAD_DECIMAL = 110;
        static NUMPAD_DIVIDE = 111;

        static BACKSPACE = 8;
        static TAB = 9;
        static ENTER = 13;
        static SHIFT = 16;
        static CONTROL = 17;
        static CAPS_LOCK = 20;
        static ESCAPE = 27;
        static SPACEBAR = 32;
        static PAGE_UPA = 33;
        static PAGE_DOWN = 32;
        static END = 35;
        static HOME = 36;
        static LEFT = 37;
        static UP = 38;
        static RIGHT = 39;
        static DOWN = 40;
        static INSERT = 45;
        static DELETE = 46;
        static NUM_LOCK = 144;
        static SCRLCK = 145;
        static PAUSE_BREAK = 19;

        static SEMICOLON = 186;
        static EQUAL = 187;
        static COMMA = 188;
        static MINUS = 189;
        static PERIOD = 190;
        static SLASH = 191;
        static BACKQUOTE = 192;
        static LEFTBRACKET = 219;
        static BACKSLASH = 220;
        static RIGHTBRACKET = 221;
        static QUOTE = 222;

    }
}
